AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LearnIA User Management Lambda MVP

Parameters:
  Environment:
    Type: String
    Default: dev
  DatabaseUrl:
    Type: String
    NoEcho: true
  JWTSecret:
    Type: String
    NoEcho: true
  CorsOrigin:
    Type: String
    Default: "*"

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64
    CodeUri: src/
    Handler: app.lambdaHandler
    Environment:
      Variables:
        NODE_ENV: !Ref Environment
        DATABASE_URL: !Ref DatabaseUrl
        JWT_SECRET: !Ref JWTSecret
        JWT_EXPIRES_IN: "24h"
        BCRYPT_ROUNDS: "12"
        CORS_ORIGIN: !Ref CorsOrigin

Resources:
  UserManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub learnia-user-management-${Environment}
      Description: User Management MVP
      Policies:
        - AWSLambdaBasicExecutionRole
        # Add additional permissions here if the Lambda needs them
      Events:
        Register:
          Type: Api
          Properties:
            Path: /auth/register
            Method: POST
        Login:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST
        Logout:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: POST
        GetProfile:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
        UpdateProfile:
          Type: Api
          Properties:
            Path: /users/{id}/profile
            Method: PUT
        Dashboard:
          Type: Api
          Properties:
            Path: /users/{id}/dashboard
            Method: GET
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: GET
        Info:
          Type: Api
          Properties:
            Path: /info
            Method: GET

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt UserManagementFunction.Arn